/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SentryExamplePageRouteImport } from './routes/sentry-example-page'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as AiInfoRouteImport } from './routes/ai-info'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/_index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions/$slug'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings/subscription'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsConnectionsRouteImport } from './routes/settings/connections'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as FrameworksSlugRouteImport } from './routes/frameworks/$slug'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SentryExamplePageRoute = SentryExamplePageRouteImport.update({
  id: '/sentry-example-page',
  path: '/sentry-example-page',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInfoRoute = AiInfoRouteImport.update({
  id: '/ai-info',
  path: '/ai-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => SettingsRoute,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const FrameworksSlugRoute = FrameworksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FrameworksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-info': typeof AiInfoRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/import': typeof ImportRoute
  '/pricing': typeof PricingRoute
  '/sentry-example-page': typeof SentryExamplePageRoute
  '/settings': typeof SettingsIndexRoute
  '/showcase': typeof ShowcaseRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-info': typeof AiInfoRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/import': typeof ImportRoute
  '/pricing': typeof PricingRoute
  '/sentry-example-page': typeof SentryExamplePageRoute
  '/settings': typeof SettingsIndexRoute
  '/showcase': typeof ShowcaseRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-info': typeof AiInfoRoute
  '/frameworks': typeof FrameworksRouteWithChildren
  '/import': typeof ImportRoute
  '/pricing': typeof PricingRoute
  '/sentry-example-page': typeof SentryExamplePageRoute
  '/settings': typeof SettingsRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/frameworks/$slug': typeof FrameworksSlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/_index': typeof SettingsIndexRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-info'
    | '/frameworks'
    | '/import'
    | '/pricing'
    | '/sentry-example-page'
    | '/settings'
    | '/showcase'
    | '/solutions'
    | '/frameworks/$slug'
    | '/projects/$projectId'
    | '/settings/connections'
    | '/settings/profile'
    | '/settings/subscription'
    | '/solutions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-info'
    | '/frameworks'
    | '/import'
    | '/pricing'
    | '/sentry-example-page'
    | '/settings'
    | '/showcase'
    | '/solutions'
    | '/frameworks/$slug'
    | '/projects/$projectId'
    | '/settings/connections'
    | '/settings/profile'
    | '/settings/subscription'
    | '/solutions/$slug'
  id:
    | '__root__'
    | '/'
    | '/ai-info'
    | '/frameworks'
    | '/import'
    | '/pricing'
    | '/sentry-example-page'
    | '/settings'
    | '/showcase'
    | '/solutions'
    | '/frameworks/$slug'
    | '/projects/$projectId'
    | '/settings/_index'
    | '/settings/connections'
    | '/settings/profile'
    | '/settings/subscription'
    | '/solutions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInfoRoute: typeof AiInfoRoute
  FrameworksRoute: typeof FrameworksRouteWithChildren
  ImportRoute: typeof ImportRoute
  PricingRoute: typeof PricingRoute
  SentryExamplePageRoute: typeof SentryExamplePageRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentry-example-page': {
      id: '/sentry-example-page'
      path: '/sentry-example-page'
      fullPath: '/sentry-example-page'
      preLoaderRoute: typeof SentryExamplePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-info': {
      id: '/ai-info'
      path: '/ai-info'
      fullPath: '/ai-info'
      preLoaderRoute: typeof AiInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/_index': {
      id: '/settings/_index'
      path: ''
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frameworks/$slug': {
      id: '/frameworks/$slug'
      path: '/$slug'
      fullPath: '/frameworks/$slug'
      preLoaderRoute: typeof FrameworksSlugRouteImport
      parentRoute: typeof FrameworksRoute
    }
  }
}

interface FrameworksRouteChildren {
  FrameworksSlugRoute: typeof FrameworksSlugRoute
}

const FrameworksRouteChildren: FrameworksRouteChildren = {
  FrameworksSlugRoute: FrameworksSlugRoute,
}

const FrameworksRouteWithChildren = FrameworksRoute._addFileChildren(
  FrameworksRouteChildren,
)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInfoRoute: AiInfoRoute,
  FrameworksRoute: FrameworksRouteWithChildren,
  ImportRoute: ImportRoute,
  PricingRoute: PricingRoute,
  SentryExamplePageRoute: SentryExamplePageRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
